# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  displayName: 'Use Node 14.17'
  inputs:
    versionSpec: 14.17

- task: BrowserStackConfig@0
  inputs:
    BrowserStackServiceEndPoint: 'BrowserStack Arvind Connection'
- script: |
    npm install
  displayName: 'npm install and build'

- script: |
    npm run parallel
  displayName: 'run on browserstack'

- task: BrowserStackResults@1
  inputs:
    browserstackProduct: 'automate'
