# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
- task: BrowserStackConfig@0
  inputs:
    BrowserStackServiceEndPoint: 'BrowserStack Connection'
    browserstackLocal: true
- script: |
    npm install
  displayName: 'npm install and build'

- script: |
    npm run parallel
  displayName: 'run on browserstack'
- task: BrowserStackStopLocal@0
- task: BrowserStackResults@1
  inputs:
    browserstackProduct: 'automate'
